default_platform(:android)

platform :android do
desc "Runs all the tests"
lane :test do
print "Fastlane works successfully"
end

desc "Prepare Android Debug Build"
lane :build_debug_android do
gradle(
task: "assembleDebug",

)
end

end